name: CICD

on:
 workflow_dispatch:
  inputs:
    environment:
     description: This is the environment where this workflow runs
     default: 'dev'
     type: choice
     options:
       - dev
       - prod
       - staging
jobs:

  Code:
   runs-on: ubuntu-latest
   steps:
     - name: checkout code
       run: echo "Code Clone from Github"
       
  Build:
   needs: [Code]
   runs-on: ubuntu-latest
   steps:
     - name: Build Docker Container
       run: echo "Docker Container build"
       
  Test:
   needs: [Build]
   runs-on: ubuntu-latest
   steps:
    - name: Test the container
      run: echo "Container tested"

  Deploy:
   needs: [Test,Build]
   runs-on: ubuntu-latest
   steps:
    - name: Deploy the apps
      run: echo "Apps are deployed"
